Name     : Muhammad Shaffay
Roll No. : 20i-2391
Section  : AI-K

# Including Libraries

In [1]:
import pandas as pd
import numpy as np
from numpy import random

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
import lightgbm as lgb

# Reading Dataset

In [2]:
dataset = pd.read_excel(r"Training_Data.xlsx")

# Basic Analysis

In [3]:
dataset.shape

(8481, 57)

In [4]:
string_columns = dataset.dtypes[dataset.dtypes == np.object]
string_columns

C:\Users\MUHAMM~1\AppData\Local\Temp/ipykernel_2188/833859135.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  string_columns = dataset.dtypes[dataset.dtypes == np.object]

EncounterId                           object
DischargeDisposision                  object
Gender                                object
Race                                  object
DiabetesMellitus                      object
ChronicKidneyDisease                  object
Anemia                                object
Depression                            object
ChronicObstructivePulmonaryDisease    object
ReadmissionWithin_90Days              object
dtype: object

In [5]:
dataset.head()

,PatientId,EncounterId,DischargeDisposision,Gender,Race,DiabetesMellitus,ChronicKidneyDisease,Anemia,Depression,ChronicObstructivePulmonaryDisease,...,BetaBlockers,Diuretics,TotalMedicine,CardiacTroponin,Hemoglobin,SerumSodium,SerumCreatinine,BNP,NT-proBNP,ReadmissionWithin_90Days
0,4200412,199171333,Home,Male,White,DM,NaN,Anemia,NaN,COPD,...,0,0,0,0.0,0.00,0.0,0.00,0.0,0.0,Yes
1,4055894,26704337,Home,Male,White,DM,CKD,Anemia,Depression,COPD,...,1,5,8,0.0,0.00,0.0,1.54,0.0,0.0,No
2,4867407,60388216,Home,Male,White,DM,CKD,Anemia,NaN,COPD,...,1,1,2,0.0,10.20,0.0,0.00,0.0,0.0,No
3,4058064,274642265,Hospice - Home,Female,White,DM,NaN,Anemia,NaN,COPD,...,0,0,0,0.0,0.00,132.0,0.00,0.0,0.0,No
4,4150623,70000001557327,SNF,Female,White,NaN,NaN,Anemia,NaN,COPD,...,0,0,0,0.0,7.26,0.0,0.00,0.0,0.0,No

In [6]:
dataset.describe()

,PatientId,Age,ChronicDiseaseCount,LengthOfStay,EmergencyVisit,InpatientVisit,OutpatientVisit,TotalVisits,BMIMin,BMIMax,...,ARBs,BetaBlockers,Diuretics,TotalMedicine,CardiacTroponin,Hemoglobin,SerumSodium,SerumCreatinine,BNP,NT-proBNP
count,8.481000e+03,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,...,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000,8481.000000
mean,4.318117e+06,73.548049,12.213772,6.081123,5.109067,7.115788,1.944818,14.169673,12.392919,12.514962,...,0.132649,0.423653,0.492277,1.229926,0.146595,1.335670,21.258704,0.446371,9.306721,11.627343
std,3.385619e+05,12.420458,4.906862,7.535437,7.204707,6.838883,5.093908,13.449911,16.129312,16.309149,...,0.442411,0.714804,0.941054,1.720905,3.261128,3.652213,49.947666,1.103418,481.311690,415.380868
min,4.032771e+06,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.062212e+06,66.000000,9.000000,3.000000,1.000000,3.000000,0.000000,5.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.146281e+06,75.000000,12.000000,4.000000,3.000000,5.000000,0.000000,10.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,4.624480e+06,82.000000,16.000000,7.000000,6.000000,9.000000,0.000000,19.000000,26.780000,27.120000,...,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.480000,0.000000,0.000000
max,5.455820e+06,102.000000,28.000000,356.000000,99.000000,95.000000,53.000000,142.000000,106.780000,108.540000,...,8.000000,8.000000,8.000000,18.000000,207.836667,18.550000,174.000000,14.387500,32733.000000,26900.000000

# Pre Processing

In [7]:
def PreProcesing(): # filing nans
    dataset['DiabetesMellitus'].fillna('0',inplace=True)
    dataset['ChronicKidneyDisease'].fillna('0',inplace=True)
    dataset['Anemia'].fillna('0',inplace=True)
    dataset['Depression '].fillna('0',inplace=True)
    dataset['ChronicObstructivePulmonaryDisease'].fillna('0',inplace=True)

In [8]:
PreProcesing()

In [9]:
def encounter(dataset): # dealing with encounterID column
    
    encounterid = []
    for x in dataset["EncounterId"]:
        if type(x) == str:
            x = 0
        if x > 10000000000:
            x = 0    
        encounterid.append(x)
    
    dataset['EncounterId'] = encounterid

In [10]:
encounter(dataset)

In [11]:
def encoding(dataset): # encoding strings
    labelE = LabelEncoder()

    columns = ['DischargeDisposision','EncounterId','Gender','Race','DiabetesMellitus','ChronicKidneyDisease','Anemia','Depression ','ChronicObstructivePulmonaryDisease','ReadmissionWithin_90Days']
    dataset[columns] = dataset[columns].apply(labelE.fit_transform)

In [12]:
encoding(dataset)

# Model Trained On Complete Dataset

In [13]:
x = dataset.drop('ReadmissionWithin_90Days' , axis = 1)
y = dataset['ReadmissionWithin_90Days']

In [14]:
x_train , x_test , y_train , y_test = train_test_split(x , y)

In [15]:
model = lgb.LGBMClassifier(learning_rate = 0.09, max_depth=25, random_state = 42)
model.fit(x_train, y_train)
prediction = model.predict(x_test)

In [16]:
print ("Accuracy : " , accuracy_score(y_test,prediction)*100)
print("Report : \n", classification_report(y_test, prediction))

print("F1 Score : ",f1_score(y_test, prediction, average='macro')*100)
print("Confusion Matrix :\n" , confusion_matrix(y_test,prediction))

Accuracy :  71.0985384252711
Report :
               precision    recall  f1-score   support

           0       0.77      0.85      0.81      1502
           1       0.51      0.37      0.43       619

    accuracy                           0.71      2121
   macro avg       0.64      0.61      0.62      2121
weighted avg       0.69      0.71      0.70      2121

F1 Score :  61.668716134763116
Confusion Matrix :
 [[1280  222]
 [ 391  228]]

# Fitness Function

In [17]:
def FitnessFunction(ffX , ffY): # LGBM checks accuracies
    
    ffx_train , ffx_test , ffy_train , ffy_test = train_test_split(ffX ,ffY)
    model = lgb.LGBMClassifier(learning_rate = 0.09, max_depth=25, random_state = 42)
    model.fit(ffx_train, ffy_train)
    prediction = model.predict(ffx_test)
    accuracy = accuracy_score(ffy_test,prediction)*100

    return accuracy

# Population Initialization

In [18]:
patterens = []

In [19]:
def population_initialization(): # making intial population
    sX = dataset.drop('ReadmissionWithin_90Days' , axis = 1)
    sY = dataset['ReadmissionWithin_90Days']
    
    columns = dataset.columns
    selected = random.randint(2, size=(56))
    
    modified_dataset = pd.DataFrame()
    for i in range(56):
        if selected[i] == 1:
            modified_dataset[columns[i]] = sX[columns[i]]
    patterens.append(selected) 
    
    #population_initialization_display(selected)
    return FitnessFunction(modified_dataset , sY)

In [20]:
def population_initialization_display(selected):
    print("Patteren : " , selected)

# Selection

In [21]:
accuracies = []

In [22]:
def Sorting(accuracies , patterens): # Sorting both accuracies , patterens list
    for i in range(len(accuracies)): 
        for j in range(len(accuracies)):
            temp = 0
            if accuracies[i] < accuracies[j]:
                temp = accuracies[i]
                accuracies[i] = accuracies[j]
                accuracies[j] = temp

                temp = 0
                temp = patterens[i]
                patterens[i] = patterens[j]
                patterens[j] = temp

In [23]:
def generation(): # making first generation
    for i in range(60):
        acc = population_initialization()
        accuracies.append(acc)

In [24]:
def poping(pop_elements): #v poping low accuracy members
    for i in range(pop_elements):
        accuracies.pop(0)
        patterens.pop(0)

In [25]:
def print_selected():
    for i in range(len(patterens)):
        print("Selected Patteren " , i , " : " , patterens[i])

# Crossover

In [26]:
def crossover_accuracy(crossovered): # calculating accuracy of crossovered childrens
    cX = dataset.drop('ReadmissionWithin_90Days' , axis = 1)
    cY = dataset['ReadmissionWithin_90Days']
    
    modified_dataset = pd.DataFrame()
    columns = dataset.columns

    for i in range(56):
        if crossovered[i] == 1:
            modified_dataset[columns[i]] = cX[columns[i]]

    return FitnessFunction(modified_dataset , cY)

In [27]:
def crossover(): # crossover implementation
    crossovered = []
    
    for i in range(0 , len(accuracies) - 1 , 2):
        list1 = patterens[i]
        list2 = patterens[i + 1]
        
        rand_num = random.randint(0,56)
        
        list3 = []
        list4 = []
        
        for j in range(rand_num):
            list3.append(list1[j])
            list4.append(list2[j])

        for k in range(rand_num , 56):
            list3.append(list2[k])
            list4.append(list1[k])
            
        patterens.append(list3)
        patterens.append(list4)
        crossovered.append(list3)
        crossovered.append(list4)        
        
        #print_crossovers(rand_num , list1, list2, list3, list4)
    for x in range(len(crossovered)):
         accuracies.append(crossover_accuracy(crossovered[x]))

In [28]:
def print_crossovers(rand_num , list1 , list2 , list3, list4):
    print("Splitting Point : " , rand_num)
    print("Parent 1 : " , list1)
    print("Parent 2 : " , list2)
    print("Parent 3 : " , list3)
    print("Parent 4 : " , list4)
    print("\n")

# Mutation

In [29]:
def mutation_check(): # checking need for mutation
    rand_num = random.randint(0,100)
    
    if rand_num < 50:
        rand_num = random.randint(0 , 60)
        mutation(rand_num)

In [30]:
def mutation(index): # mutation implementation
    rand_num = random.randint(0 , 56)

    #print("Index : " , index)
    #print("Changing At Column Number : " , rand_num)
    
    #print("Non-Mutated patteren : " ,  patterens[index])
    if patterens[index][rand_num] == 1:
        patterens[index][rand_num] = 0
        
    elif patterens[index][rand_num] == 0:
        patterens[index][rand_num] = 1
        
    #print("Mutated patteren : " ,  patterens[index])

In [31]:
def same(list1 , list2): # checking if 2 lists are same
    counter = 0
    
    for i in range(len(list1)):
        if list1[i] == list2[i]:
            counter += 1
            
    if counter == len(list1):
        return True
    else:
        return False

In [32]:
def mutation_checksame(): # checking need of mutation after mutation
    for i in range(0 , len(patterens)):
        if (i+1) < len(patterens):
            for j in range(i + 1 , len(patterens)):
                if same(patterens[i] , patterens[j]) == True:
                    mutation(j)
                    mutation_checksame()

# Genetic Algorithim

In [33]:
def print_best(best_accuracy , best_chromosome):
    for i in range(len(best_accuracy)): # Printing
        print("Accuracy : " , best_accuracy[i])
        print("Patteren : " , best_chromosome[i])
        print("\n")

In [34]:
def make_dataframe(best_accuracy , best_chromosome): # making dataframe of patterens and accuracies
    column_names = dataset.columns
    column_names = column_names[0:56]
    
    patterens_dataframe = pd.DataFrame(best_chromosome , columns=column_names)
    patterens_dataframe['Acuuracies'] = best_accuracy
    patterens_dataframe.head(5)
    return patterens_dataframe

In [35]:
def GeneticAlgorithim(): # GA
    
    best_chromosome = []
    best_accuracy = []
    
    generation() # Selection
    Sorting(accuracies , patterens)
    poping(30)
    
    for i in range(200): # Termination Criteria 1
        
        crossover() # Crossover
        mutation_check()# mutation
        mutation_checksame# if any combination is same
        
        Sorting(accuracies , patterens)
        poping(30)
        
        best_chromosome.append(patterens[0])
        best_accuracy.append(accuracies[0])
        
        if i > 20: # Termination Criteria 2
            if best_accuracy[i] == best_accuracy[i - 1]:
                break
        
        if accuracies[0] == 90: # Termination Criteria 3
            break
            
    Sorting(best_accuracy , best_chromosome)
    #print_best(best_accuracy , best_chromosome)
    return make_dataframe(best_accuracy , best_chromosome)

In [36]:
patterens_dataframe = GeneticAlgorithim()
patterens_dataframe.tail(5)

Non-Mutated patteren :  [1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
Non-Mutated patteren :  [0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1]
Non-Mutated patteren :  [1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0]
Non-Mutated patteren :  [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]
Non-Mutated patteren :  [1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
Non-Mutated patteren :  [0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0]
Non-Mutated patteren :  [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1]
Non-Mutated patteren :  [0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1]
Non-Mutated patteren :  [0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
Non-Mutated patteren :  [0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]
Non-Mutated patteren :  [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]
Non-Mutated patteren :  [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1]
Non-Mutated patteren :  [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]
Non-Mutated patteren :  [0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0]
Non-Mutated patteren :  [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0]

,PatientId,EncounterId,DischargeDisposision,Gender,Race,DiabetesMellitus,ChronicKidneyDisease,Anemia,Depression,ChronicObstructivePulmonaryDisease,...,BetaBlockers,Diuretics,TotalMedicine,CardiacTroponin,Hemoglobin,SerumSodium,SerumCreatinine,BNP,NT-proBNP,Acuuracies
0,1,1,0,1,0,0,1,0,1,0,...,0,0,1,0,1,0,1,0,1,72.041490
1,0,1,1,0,1,1,1,0,0,1,...,0,1,0,0,1,0,1,1,0,72.512966
2,1,0,0,0,0,1,1,1,0,1,...,1,1,0,1,0,1,0,0,0,72.607261
3,1,1,1,0,1,0,1,0,0,1,...,1,1,1,0,0,1,0,0,0,72.701556
4,1,1,1,0,1,0,1,0,0,1,...,1,0,1,1,0,1,0,1,1,72.984441
5,0,1,0,1,0,1,0,1,1,0,...,1,1,1,1,1,1,1,0,1,73.125884
6,0,1,1,0,1,1,1,0,0,1,...,1,1,1,1,1,1,1,0,1,73.173032
7,1,1,1,0,0,1,1,0,1,0,...,1,1,1,1,1,1,1,0,1,73.361622
8,1,0,1,1,0,1,1,1,0,1,...,1,0,1,1,0,1,0,1,1,73.408769
9,0,1,1,1,0,0,0,1,0,1,...,0,0,1,0,1,0,1,0,1,73.408769
10,0,1,1,0,1,1,1,1,1,1,...,0,1,0,1,1,1,0,1,0,73.503065
11,0,1,1,1,0,0,0,1,0,0,...,0,1,1,1,1,1,0,0,1,73.550212
12,0,1,1,0,1,1,1,0,0,1,...,1,1,0,1,0,1,0,0,0,73.644507
13,0,1,1,1,0,0,0,1,0,0,...,0,0,1,0,1,0,1,0,1,73.691655
14,0,1,1,1,0,0,0,1,0,0,...,0,0,1,1,1,1,0,1,1,73.691655
15,0,1,1,1,0,0,0,0,0,1,...,1,1,1,1,1,1,1,0,1,73.738802
16,0,1,1,1,0,1,1,1,0,1,...,1,1,1,1,1,1,1,0,1,73.738802
17,0,1,1,0,0,1,1,0,0,1,...,1,0,0,1,0,0,0,0,0,73.738802
18,1,0,1,1,0,1,1,1,0,1,...,1,1,1,1,1,1,1,0,1,73.738802
19,1,1,1,0,1,0,1,0,0,1,...,1,0,0,1,0,0,0,0,0,73.738802
20,1,0,1,1,0,1,1,1,0,1,...,1,1,1,1,1,1,1,0,1,73.738802
21,0,1,1,0,0,1,1,0,0,1,...,1,0,0,1,0,0,0,0,0,73.785950
22,1,1,1,0,1,0,1,0,0,1,...,1,0,0,1,0,0,0,0,0,73.833098
23,0,1,1,0,1,1,1,0,0,1,...,0,1,0,1,1,1,0,1,0,73.880245
24,0,1,1,0,1,1,1,0,0,1,...,0,1,0,1,1,1,0,1,0,73.880245